version: '3'

volumes:
  mariadb-volume:
  wordpress-volume:

networks:
  inception-network:

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx_img
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - inception-network
    ports:
      - "443:443"
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb_img
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception-network
    env_file:
      - ./.env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: wordpress_img
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - inception-network
    env_file:
      - ./.env
    restart: unless-stopped